language: ruby
cache: bundler
before_script:
  - gem update --remote bundler
  - gem update --system
  - RAILS_ENV=test bin/rails db:create db:schema:load
script:
  - bin/rails test
install: bundle install --without production development
